<script lang="ts">
  import Article from "$lib/site/Article.svelte";
</script>

<Article title="Privacy and browser storage" intro="TopoStack stores project settings in your browser and requests the map data needed to create your artwork. No account is required.">
  <h2>Your projects</h2>
  <p>Project settings are stored in this browser's IndexedDB. If a saved project cannot be read, a copy is kept there as a backup before autosave replaces it. Depth charts you trace are stored there too, and are never uploaded: they travel only inside the project files you export. Your theme, which studio menu sections are open, and the newest release you have seen in the changelog are stored in localStorage. Export a settings backup before clearing browser storage. Downloaded files remain wherever you choose to save them.</p>
  <p>A share link contains the whole design, including its location, name, custom markers and paths, after the <code>#</code> in the address. Browsers do not send that part of a link to TopoStack, but anyone you give the link to can read it, and apps you paste it into may store it.</p>
  <h2>Map and platform services</h2>
  <p>Place searches are sent through the TopoStack map API to Geoapify. The search text is part of the request URL. Results are cached by TopoStack for 24 hours under a SHA-256 hash of the normalized query, and your browser may also cache them for up to a day. The hash is a lookup key, not a privacy protection: common searches can be recovered by guessing.</p>
  <p>Generating a project requests the elevation tiles, map features, lake outlines and lake-depth data for your selected area from TopoStack's API and storage. That reveals the area to TopoStack. Where a terrain tile is not already cached, TopoStack's API fetches it from Mapzen without passing on your browser's details. Map features come from a copy of Protomaps/OpenStreetMap data hosted by TopoStack. The only map service your browser contacts directly is OpenFreeMap, which draws the studio's reference map and receives ordinary connection information.</p>
  <p>In Atomm, the platform's SDK script is loaded from Atomm's servers. TopoStack uses it to read the interface language, show notifications and send artwork to the platform. TopoStack does not read or store an Atomm user profile or token. Files you hand to Atomm are processed by that platform.</p>
  <h2>Visits and successful use</h2>
  <p>The production website uses Cloudflare Web Analytics and a small first-party usage endpoint to understand whether visitors open the studio, generate usable real terrain and prepare fabrication exports. Each usage event contains only fixed categories: the step (such as studio opened, generation started or export prepared), the public landing page, acquisition source, the campaign and medium of a link we published (such as a launch post) when the link carries one, a small or large screen width, output type, and whether the export was downloaded or sent to Atomm. Events do not contain project names, coordinates, search text, custom map data or a persistent user identifier.</p>
  <p>The landing page and acquisition category are kept in this tab's session storage, with a timestamp and whether the landing page and studio have been counted, so they follow navigation into the studio. After 30 minutes of inactivity they are replaced on the next event, and they are removed when the tab session ends. Usage collection is best effort; blocked requests do not affect generation or export. TopoStack's own usage events honor Do Not Track and Global Privacy Control; Cloudflare Web Analytics follows Cloudflare's policies.</p>
  <p>Cloudflare hosts the site and API. Its request logs and traces may contain metadata such as IP addresses and requested URLs, including search text, for troubleshooting. The API applies rate limits keyed on your IP address (or its IPv6 /64 network). The restricted usage-event fields do not change what hosting or map providers need to process requests.</p>
  <h2>AI assistants and the API</h2>
  <p>When you use TopoStack through an AI assistant or the public API, the assistant's service sends TopoStack the request it composed: the place or area, the model's size and settings, and any title or marker names. TopoStack uses it to answer and does not store it. Request logs record the address path, status and timing, not the request body; rate limits are keyed on the address of the service making the request, which for a chat assistant is usually the assistant's provider rather than you. Place searches made by an assistant are handled like searches in the studio, as described above.</p>
  <p>An in-chat preview runs inside your assistant's app and requests the same terrain and map data from TopoStack as the studio does, which reveals the area to TopoStack. Your conversation itself stays with your assistant's provider and its privacy terms. A studio link an assistant gives you works like any share link.</p>
  <h2>Feedback</h2>
  <p>Feedback drafts stay in memory in the current page until you send them. Sending emails the report privately to the TopoStack maintainer through Cloudflare's email service; it is not published. An email address is optional and used only to reply to that report. Optional diagnostic context includes coordinates, settings, data sources, up to 12 lake names and identifiers, and warning codes; you can review it before sharing. Project names and custom markers are excluded. If you choose to continue on GitHub instead, the report is placed in a prefilled link, you sign in and submit it there, and the issue is public.</p>
  <h2>External links</h2>
  <p>GitHub, PayPal, Atomm and the linked data providers apply their own privacy terms when you use them. Questions about TopoStack can be sent with the Feedback button or raised through the <a href="https://github.com/Echo-Foxtrot-Works/topostack/issues">project's issue tracker</a>; avoid posting private project information in a public issue.</p>
</Article>
