"""Write the TIN parity fixture for @topostack/chart-trace.

packages/chart-trace/src/grid.ts ports contour_grid so traced charts can be
gridded exactly like the published contour surveys. This runs the real
contour_grid on a seeded synthetic lake and records its input and output;
grid.test.ts must reproduce the output to the centimetre.

    python scripts/data-build/make-chart-trace-fixture.py
"""
import json
import math
from pathlib import Path

import numpy as np
from shapely.geometry import Polygon

from survey_regions import contour_grid

OUTPUT = Path(__file__).resolve().parents[2] / 'packages/chart-trace/src/fixtures/tin-parity.json'
RESOLUTION = 20


def ring(rng, cx, cy, rx, ry, spacing, wobble):
    """An irregular closed ring; jitter keeps vertices off cocircular positions so the triangulation is unique."""
    count = max(12, int(math.pi * (rx + ry) / spacing))
    phase = rng.uniform(0, 2 * math.pi)
    points = []
    for index in range(count):
        angle = 2 * math.pi * index / count
        scale = 1 + 0.08 * math.sin(3 * angle + phase)
        points.append([
            round(cx + rx * scale * math.cos(angle) + rng.normal(0, wobble), 3),
            round(cy + ry * scale * math.sin(angle) + rng.normal(0, wobble), 3),
        ])
    return points


def main():
    rng = np.random.default_rng(7)
    shore = ring(rng, 1000, 700, 900, 600, 40, 4)
    island = ring(rng, 1500, 650, 70, 50, 20, 1)
    contours = [(0.0, shore)]
    for depth, fraction, dx in [(2.0, 0.78, -30), (4.0, 0.56, -60), (6.0, 0.36, -80), (8.0, 0.18, -90)]:
        contours.append((depth, ring(rng, 1000 + dx, 700, 900 * fraction, 600 * fraction, 40, 4)))
    points = [[x, y, depth] for depth, line in contours for x, y in line]
    # A repeated vertex with a conflicting depth must be dropped, as in the port.
    points.append([contours[2][1][0][0], contours[2][1][0][1], 5.5])
    water = Polygon(shore, [island])
    values, transform = contour_grid(points, water, resolution=RESOLUTION)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps({
        'note': 'Generated by scripts/data-build/make-chart-trace-fixture.py from survey_regions.contour_grid.',
        'resolution': RESOLUTION,
        'water': [shore, island],
        'points': points,
        'layout': {'left': transform.c, 'top': transform.f, 'width': values.shape[1], 'height': values.shape[0]},
        'values': [None if not np.isfinite(value) else round(float(value), 5) for value in values.ravel()],
    }, separators=(',', ':')) + '\n')
    print(f'Wrote {OUTPUT} ({values.shape[1]}x{values.shape[0]}, {int(np.isfinite(values).sum())} water cells)')


if __name__ == '__main__':
    main()
